# Generated by Django 5.1.1 on 2024-09-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-date_taken']},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='level',
        ),
        migrations.AddField(
            model_name='exam',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='ExamResult',
        ),
    ]
