# Generated by Django 5.1.1 on 2024-10-06 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_supervisorquestion_supervisorsubject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisorquestion',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='supervisorquestion',
            name='level',
        ),
        migrations.RemoveField(
            model_name='supervisorquestion',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='supervisorquestion',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='supervisorquestion',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='supervisorquestion',
            name='option4',
        ),
        migrations.RemoveField(
            model_name='supervisorquestion',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='supervisorquestion',
            name='subject',
        ),
        migrations.AddField(
            model_name='supervisorquestion',
            name='exam',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='SupervisorExam', to='exams.subject'),
        ),
        migrations.AddField(
            model_name='supervisorquestion',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exams.question'),
        ),
        migrations.CreateModel(
            name='SupervisorExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_questions', models.CharField(max_length=200)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SupervisorSubject',
        ),
    ]
