# Generated by Django 5.1.1 on 2024-10-06 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_remove_supervisorquestion_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorquestion',
            name='exam',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='SupervisorExam', to='exams.supervisorexam'),
        ),
    ]
