# Generated by Django 5.1.1 on 2024-10-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_supervisorquestion_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisorquestion',
            name='user',
        ),
    ]
