# Generated by Django 5.1.1 on 2024-10-06 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_remove_supervisorquestion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedexams',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.supervisorexam'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.supervisorexam'),
        ),
    ]
