# Generated by Django 5.1.1 on 2024-09-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, choices=[('New Capital', 'New Capital'), ('Cairo', 'Cairo'), ('Menofia', 'Menofia')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, choices=[('Open Source PHP', 'Open Source PHP'), ('Open Source Python', 'Open Source Python')], max_length=30, null=True),
        ),
    ]
