# Generated by Django 5.0.6 on 2024-09-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_organization_remove_profile_github_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='track',
        ),
        migrations.AddField(
            model_name='user',
            name='tracks',
            field=models.ManyToManyField(blank=True, to='users.track'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
