# Generated by Django 5.0.6 on 2024-09-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_role_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('student', 'Student')], default='student', max_length=10),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
