# Generated by Django 5.0.6 on 2024-09-28 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_role_delete_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organization'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
