# Generated by Django 5.0.6 on 2024-09-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_organization_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='github',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hackerrank',
        ),
        migrations.RemoveField(
            model_name='user',
            name='leetcode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
