# Generated by Django 5.0.6 on 2024-09-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_github_user_hackerrank_user_leetcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('student', 'Student')], max_length=20),
        ),
    ]
