# Generated by Django 5.1.1 on 2024-10-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_user_tracks_track_supervisor_user_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
