# Generated by Django 5.1.1 on 2024-10-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
