# Generated by Django 5.1.1 on 2024-10-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_authorized',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
